### ISSUE TITLE
Possible typescript improvements

### ISSUE THREAD

**Issue by thetarnav** [marvinhagemeister/preact-multi-provider#8]
While shamelessly stealing your idea to [add it to solid-primitives](https://github.com/solidjs-community/solid-primitives/pull/354) we might have discovered a way to have type-validation of pairs in the `values` array without a function helper.
Raw idea: https://playground.solidjs.com/anonymous/ecff628b-ae15-4943-b1d2-fecce25ec8b9

**Comment by marvinhagemeister** [comment]
Sweeet, this is perfect!! I figured something clever with `never` might be possible, but I couldn't get it to work myself. Your solution is clever. Really like it, gonna adopt it here too. Thanks for sharing it 👍
